export interface TickerEntry {
  ticker: string;
  name: string;
}

/**
 * Utvidet tickerliste for DCF-oversikten (/dcf) — bygget fra Wikipedias liste over
 * Oslo Børs-noterte selskaper, verifisert mot Yahoo Finance (kun EQUITY-typer beholdt).
 * Brukes KUN av DCF-modulen. Fundamental analyse bruker fortsatt den mindre listen i
 * lib/tickers.ts.
 */
export const DCF_TICKERS: TickerEntry[] = [
  { ticker: "EQNR.OL", name: "Equinor" },
  { ticker: "DNB.OL", name: "DNB Bank" },
  { ticker: "TEL.OL", name: "Telenor" },
  { ticker: "AKRBP.OL", name: "Aker BP" },
  { ticker: "NHY.OL", name: "Norsk Hydro" },
  { ticker: "MOWI.OL", name: "Mowi" },
  { ticker: "YAR.OL", name: "Yara International" },
  { ticker: "ORK.OL", name: "Orkla" },
  { ticker: "SALM.OL", name: "SalMar" },
  { ticker: "KOG.OL", name: "Kongsberg Gruppen" },
  { ticker: "STB.OL", name: "Storebrand" },
  { ticker: "GJF.OL", name: "Gjensidige Forsikring" },
  { ticker: "SUBC.OL", name: "Subsea 7" },
  { ticker: "SCATC.OL", name: "Scatec" },
  { ticker: "NEL.OL", name: "Nel" },
  { ticker: "BOUV.OL", name: "Bouvet" },
  { ticker: "PGS.OL", name: "PGS" },
  { ticker: "TGS.OL", name: "TGS" },
  { ticker: "FRO.OL", name: "Frontline" },
  { ticker: "BWO.OL", name: "BW Offshore" },
  { ticker: "AUTO.OL", name: "AutoStore" },
  { ticker: "NSKOG.OL", name: "Norske Skog" },
  { ticker: "RECSI.OL", name: "REC Silicon" },
  { ticker: "ABG.OL", name: "ABG Sundal Collier Holding ASA" },
  { ticker: "ACR.OL", name: "Axactor ASA" },
  { ticker: "AFG.OL", name: "AF Gruppen ASA" },
  { ticker: "AFK.OL", name: "Arendals Fossekompani ASA" },
  { ticker: "AKER.OL", name: "Aker ASA" },
  { ticker: "AKSO.OL", name: "Aker Solutions ASA" },
  { ticker: "AKVA.OL", name: "AKVA group ASA" },
  { ticker: "AQUA.OL", name: "Aqualis ASA" },
  { ticker: "ATEA.OL", name: "Atea ASA" },
  { ticker: "AURG.OL", name: "Aurskog Sparebank" },
  { ticker: "AUSS.OL", name: "Austevoll Seafood ASA" },
  { ticker: "B2I.OL", name: "B2 Impact ASA" },
  { ticker: "BAKKA.OL", name: "P/F Bakkafrost" },
  { ticker: "BMA.OL", name: "Byggma ASA" },
  { ticker: "BOR.OL", name: "Borgestad ASA" },
  { ticker: "BRG.OL", name: "Borregaard ASA" },
  { ticker: "BWLPG.OL", name: "BW LPG Limited" },
  { ticker: "DNO.OL", name: "DNO ASA" },
  { ticker: "EIOF.OL", name: "Eidesvik Offshore ASA" },
  { ticker: "ELK.OL", name: "Elkem ASA" },
  { ticker: "ENDUR.OL", name: "Endúr ASA" },
  { ticker: "ENTRA.OL", name: "Entra ASA" },
  { ticker: "EPR.OL", name: "Europris ASA" },
  { ticker: "GOD.OL", name: "Goodtech ASA" },
  { ticker: "GSF.OL", name: "Grieg Seafood ASA" },
  { ticker: "GYL.OL", name: "Gyldendal ASA" },
  { ticker: "HAVI.OL", name: "Havila Shipping ASA" },
  { ticker: "HELG.OL", name: "SpareBank 1 Helgeland" },
  { ticker: "HEX.OL", name: "Hexagon Composites ASA" },
  { ticker: "HSPG.OL", name: "Høland og Setskog Sparebank" },
  { ticker: "IDEX.OL", name: "IDEX Biometrics ASA" },
  { ticker: "IOX.OL", name: "Interoil Exploration and Production ASA" },
  { ticker: "JIN.OL", name: "Jinhui Shipping and Transportation Limited" },
  { ticker: "KID.OL", name: "Kid ASA" },
  { ticker: "KIT.OL", name: "Kitron ASA" },
  { ticker: "KOA.OL", name: "Kongsberg Automotive ASA" },
  { ticker: "LSG.OL", name: "Lerøy Seafood Group ASA" },
  { ticker: "MEDI.OL", name: "Medistim ASA" },
  { ticker: "MELG.OL", name: "Melhus Sparebank" },
  { ticker: "MING.OL", name: "SpareBank 1 SMN" },
  { ticker: "MORG.OL", name: "Sparebanken Møre" },
  { ticker: "MPCC.OL", name: "MPC Container Ships ASA" },
  { ticker: "MULTI.OL", name: "Multiconsult ASA" },
  { ticker: "NAPA.OL", name: "Napatech A/S" },
  { ticker: "NAS.OL", name: "Norwegian Air Shuttle ASA" },
  { ticker: "NAVA.OL", name: "Navamedic ASA" },
  { ticker: "NEXT.OL", name: "NEXT Biometrics Group ASA" },
  { ticker: "NOD.OL", name: "Nordic Semiconductor ASA" },
  { ticker: "NONG.OL", name: "SpareBank 1 Nord-Norge" },
  { ticker: "NRC.OL", name: "NRC Group ASA" },
  { ticker: "ODF.OL", name: "Odfjell SE" },
  { ticker: "ODFB.OL", name: "Odfjell SE" },
  { ticker: "ODL.OL", name: "Odfjell Drilling Ltd." },
  { ticker: "PARB.OL", name: "Pareto Bank ASA" },
  { ticker: "PEN.OL", name: "Panoro Energy ASA" },
  { ticker: "PEXIP.OL", name: "Pexip Holding ASA" },
  { ticker: "PHO.OL", name: "Photocure ASA" },
  { ticker: "PLT.OL", name: "poLight ASA" },
  { ticker: "POL.OL", name: "Polaris Media ASA" },
  { ticker: "PRS.OL", name: "Prosafe SE" },
  { ticker: "PSE.OL", name: "Petrolia SE" },
  { ticker: "QEC.OL", name: "Questerre Energy Corporation" },
  { ticker: "REACH.OL", name: "Reach Subsea ASA" },
  { ticker: "RING.OL", name: "SpareBank 1 Ringerike Hadeland" },
  { ticker: "SATS.OL", name: "Sats ASA" },
  { ticker: "SBO.OL", name: "Selvaag Bolig ASA" },
  { ticker: "SDSD.OL", name: "S.D. Standard ETC Plc" },
  { ticker: "SKUE.OL", name: "Skue Sparebank" },
  { ticker: "SNI.OL", name: "Stolt-Nielsen Limited" },
  { ticker: "SOAG.OL", name: "SpareBank 1 Østfold Akershus" },
  { ticker: "SOFF.OL", name: "Solstad Offshore ASA" },
  { ticker: "SOGN.OL", name: "Sogn Sparebank" },
  { ticker: "SPOG.OL", name: "Sparebanken Øst" },
  { ticker: "SPOL.OL", name: "SpareBank 1 Østlandet" },
  { ticker: "TOM.OL", name: "Tomra Systems ASA" },
  { ticker: "VEI.OL", name: "Veidekke ASA" },
  { ticker: "VVL.OL", name: "Voss Veksel- og Landmandsbank ASA" },
  { ticker: "WSTEP.OL", name: "Webstep ASA" },
  { ticker: "WWI.OL", name: "Wilh. Wilhelmsen Holding ASA" },
  { ticker: "WWIB.OL", name: "Wilh. Wilhelmsen Holding ASA" },
  { ticker: "ZAL.OL", name: "Zalaris ASA" },
];
